//
//  MapKitLabTests.swift
//  MapKitLabTests
//
//  Created by Tanya Burke on 2/24/20.
//  Copyright © 2020 Tanya Burke. All rights reserved.
//

import XCTest
@testable import MapKitLab

class MapKitLabTests: XCTestCase {

    func testModel(){
  let jsonData = """
                   [{
    "dbn": "16K498",
    "school_name": "Brooklyn High School for Law and Technology",
    "boro": "K",
    "overview_paragraph": "The mission of Brooklyn High School for Law and Technology is to intellectually prepare, morally inspire, and socially motivate every student to become a leader in this vastly changing society. Our curriculum in biomedical science, engineering, software engineering, and law are blueprints for all students to succeed in any competitive college program. At Brooklyn High School for Law and Technology, the overall goal is to cultivate exceptional leaders prepared to serve and lead globally.",
    "school_10th_seats": "Y",
    "academicopportunities1": "iLearnNYC: Program for expanded online coursework and self-paced learning",
    "academicopportunities2": "Access to Law and Technology Programs: Youth Court, ESI, Civil Rights and Patent Law, Technology Program (provides experiences in web design)",
    "academicopportunities3": "Computer Programming, iCareers, Online courses; Volunteers mentor our scholars through community service internships",
    "academicopportunities4": "Multicultural Literature, Conflict Resolution/Peer Mediation, Debate, College and Career Prep, TV and Music Production Studio, CUNY College Now, Calculus",
    "ell_programs": "English as a New Language",
    "language_classes": "Spanish",
    "advancedplacement_courses": "AP Chemistry, AP English Language and Composition, AP English Literature and Composition, AP Environmental Science, AP Spanish",
    "diplomaendorsements": "Math",
    "neighborhood": "Bedford-Stuyvesant",
    "shared_space": "No",
    "building_code": "K987",
    "location": "1396 Broadway, Brooklyn NY 11221(40.688399, -73.920603)",
    "phone_number": "718-919-1256",
    "fax_number": "718-852-4593",
    "school_email": "Vjohnson5@schools.nyc.gov",
    "website": "bklawtech.com",
    "subway": "J, Z to Gates Ave",
    "bus": "B20, B26, B38, B46, B47, B52, B7, Q24",
    "grades2018": "9 to 12",
    "finalgrades": "9 to 12",
    "total_students": "594",
    "start_time": "8am",
    "end_time": "3pm",
    "psal_sports_boys": "Basketball, Outdoor Track",
    "psal_sports_girls": "Basketball, Indoor Track, Volleyball",
    "school_sports": "(NCAA Cleared) Boys: Baseball, Intramural Basketball, Fitness Center, Flag Football, Soccer, Softball, Track, Volleyball; Girls: Dance/Cheerleading, Double Dutch, Fitness Center, Intramural Basketball, Karate, Softball, Step Team, Track",
    "graduation_rate": "0.74",
    "attendance_rate": "0.85",
    "pct_stu_enough_variety": "0.58",
    "college_career_rate": "0.49",
    "pct_stu_safe": "0.74",
    "school_accessibility_description": "2",
    "prgdesc1": "Study of criminal, civil, and family law; politics, and social activism. Participation in internships and community service.",
    "prgdesc2": "Introduction to computer science through the use of current technology to provide students with job readiness skills.",
    "requirement1_1": "Attendance",
    "requirement2_1": "Punctuality",
    "requirement3_1": "Course Grades: English (65-100), Math (60-100), Science (64-100), Social Studies (56-100)",
    "requirement4_1": "Standardized Test Scores: English Language Arts (1.9-4.5), Math (1.5-4.5)",
    "program1": "Academy for Social Justice",
    "program2": "Computer Technology",
    "code1": "K49B",
    "code2": "K49D",
    "interest1": "Law & Government",
    "interest2": "Computer Science & Technology",
    "method1": "Screened",
    "method2": "Ed. Opt.",
    "seats9ge1": "63",
    "seats9ge2": "62",
    "grade9gefilledflag1": "N",
    "grade9gefilledflag2": "N",
    "grade9geapplicants1": "494",
    "grade9geapplicantsperseat1": "8",
    "grade9geapplicants2": "428",
    "grade9geapplicantsperseat2": "7",
    "seats9swd1": "13",
    "seats9swd2": "13",
    "grade9swdfilledflag1": "Y",
    "grade9swdfilledflag2": "Y",
    "grade9swdapplicants1": "94",
    "grade9swdapplicantsperseat1": "7",
    "grade9swdapplicants2": "89",
    "grade9swdapplicantsperseat2": "7",
    "seats101": "Yes-10",
    "seats102": "Yes-10",
    "admissionspriority11": "Open to New York City residents",
    "admissionspriority12": "Open to New York City residents",
    "primary_address_line_1": "1396 Broadway",
    "city": "Brooklyn",
    "zip": "11221",
    "state_code": "NY",
    "borough": "BROOKLYN ",
    "latitude": "40.688831",
    "longitude": "-73.920906",
    "community_board": "3",
    "council_district": "41",
    "census_tract": "375",
    "bin": "3039676",
    "bbl": "3014820001",
    "nta": "Stuyvesant Heights                                                         "
},
{
    "dbn": "15K423",
    "school_name": "Brooklyn Frontiers High School",
    "boro": "K",
    "overview_paragraph": "Brooklyn Frontiers High School serves entering ninth grade students who have fallen behind their peers by two or more years. We offer a personalized educational experience for students, recognizing the unique strengths and needs of each individual. The academic program is designed to challenge each learner and is implemented in a supportive environment that emphasizes the value of critical thinking skills, personal relationships, and student self-advocacy. We are committed to ensuring that students stretch their goals beyond graduation and gain the skills and self-confidence to successfully transition to college and careers.",
    "academicopportunities1": "Partnership with Good Shepherd Services: coaches for students to create personalized academic plans and guidance",
    "academicopportunities2": "Small classes, many co-taught by two teachers",
    "academicopportunities3": "Many opportunities for tutoring and support, both during the day and after-school",
    "academicopportunities4": "Paid Learning to Work Internships",
    "ell_programs": "English as a New Language",
    "language_classes": "French",
    "neighborhood": "DUMBO-Downtown Brooklyn",
    "shared_space": "No",
    "building_code": "K520",
    "location": "112 Schermerhorn Street, Brooklyn NY 11201(40.690007, -73.989369)",
    "phone_number": "718-722-4727",
    "fax_number": "718-722-7919",
    "school_email": "info@brooklynfrontiers.org",
    "website": "brooklynfrontiers.org",
    "subway": "2, 3, 4, 5 to Borough Hall; A, C, F, R to Jay St-MetroTech; B, Q to DeKalb Ave; G to Hoyt & Schermerhorn",
    "bus": "B103, B25, B26, B38, B41, B45, B52, B54, B57, B61, B62, B63, B65, B67",
    "grades2018": "9 to 12",
    "finalgrades": "9 to 12",
    "total_students": "168",
    "start_time": "8:20am",
    "end_time": "2:40pm",
    "addtl_info1": "College Trips; Extended Day Program; Extended Day Program (Tutoring); Internships; Online Grading System; Student Parent Orientation; Summer Orientation; Transfer Program",
    "extracurricular_activities": "After-School Academic Support, Cook for Life, Crafts, Culture Club, Dance Club, Gay-Straight Alliance, Regents Prep, Student Council, Student Leadership, Theater, Yearbook",
    "psal_sports_boys": "Basketball",
    "school_sports": "Basketball",
    "graduation_rate": "N/A",
    "attendance_rate": "0.76",
    "pct_stu_enough_variety": "0.68",
    "college_career_rate": "N/A",
    "pct_stu_safe": "0.79",
    "transfer": "1",
    "program1": "Brooklyn Frontiers High School",
    "code1": "L69A",
    "interest1": "Humanities & Interdisciplinary",
    "method1": "Transfer",
    "seats9ge1": "33",
    "grade9gefilledflag1": "N/A - transfer school",
    "grade9geapplicants1": "31",
    "grade9geapplicantsperseat1": "1",
    "seats9swd1": "32",
    "grade9swdfilledflag1": "N/A - transfer school",
    "grade9swdapplicants1": "26",
    "grade9swdapplicantsperseat1": "1",
    "seats101": "No",
    "eligibility1": "Open only to 15-16-year-old New York City residents entering high school for the first time.  Students must have a record of being held back two times in elementary and/or middle school.",
    "primary_address_line_1": "112 Schermerhorn Street",
    "city": "Brooklyn",
    "zip": "11201",
    "state_code": "NY",
    "borough": "BROOKLYN ",
    "latitude": "40.690145",
    "longitude": "-73.989132",
    "community_board": "2",
    "council_district": "33",
    "census_tract": "43",
    "bin": "3000533",
    "bbl": "3001690009",
    "nta": "DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill                           "
},
{
    "dbn": "03M291",
    "school_name": "West End Secondary School",
    "boro": "M",
    "overview_paragraph": "We promote and support scholarly endeavors through a rich and varied curriculum, emphasizing our core values of creativity, compassion, wonder, and resilience. Through an interdisciplinary approach, utilizing New York City as a learning lab, students experience rigorous coursework through authentic expeditions, which culminate in public presentations of learning. Expeditions engage students in case studies that examine and analyze compelling topics from a variety of perspectives. All students work towards achieving an Advance Regents diploma and have the opportunity to take several Advanced Placement (AP) courses. WESS offers extensive opportunities to participate in sports, clubs, course-related travel, and service learning.",
    "academicopportunities1": "Passages: Our Senior Project requires 12th grade students to present a portfolio of their learning process to their family, the faculty, and mentors",
    "ell_programs": "English as a New Language",
    "neighborhood": "Lincoln Square",
    "shared_space": "No",
    "building_code": "M837",
    "location": "227-243 West 61st Street, Manhattan NY 10023(40.772608, -73.988338)",
    "phone_number": "212-245-1506",
    "fax_number": "212-245-1291",
    "school_email": "wessadmissions@gmail.com",
    "website": "westendsecondary.com",
    "subway": "1 to 66th St-Lincoln Center; A, C, B, D to 59th St-Columbus Circle",
    "bus": "BxM2, M10, M104, M11, M12, M20, M31, M5, M57, M66, M7, M72, X12, X14, X30, X42",
    "grades2018": "6 to 10",
    "finalgrades": "6 to 10 - This school is expanding to serve grades 6 to 12.",
    "total_students": "339",
    "start_time": "9am",
    "end_time": "3:20pm",
    "addtl_info1": "College Trips; Community Service Expected; Extended Day Program; Extended Day Program (Tutoring); Internships; Multi-Session School; Online Grading System; Saturday Programs; Student Parent Orientation; Summer Bridge Program; Summer Internships; Summer Orientation",
    "graduation_rate": "N/A",
    "pct_stu_enough_variety": "0.91",
    "college_career_rate": "N/A",
    "pct_stu_safe": "0.94",
    "school_accessibility_description": "2",
    "prgdesc1": "Students engage in in-depth discipline specific Learning Expeditions that are aligned to the regents curriculum. Field experiences enhance students learning. Students engage in original research and participate in a small group advisory program called \"Crew.\"",
    "requirement1_1": "Attendance",
    "requirement2_1": "Punctuality",
    "requirement3_1": "Course Grades: Average",
    "requirement4_1": "Standardized Test Scores: Average",
    "offer_rate1": "-97% of offers went to this group",
    "program1": "West End Secondary School",
    "code1": "M92A",
    "interest1": "Humanities & Interdisciplinary",
    "method1": "Screened",
    "seats9ge1": "75",
    "grade9gefilledflag1": "Y",
    "grade9geapplicants1": "1010",
    "grade9geapplicantsperseat1": "13",
    "seats9swd1": "15",
    "grade9swdfilledflag1": "Y",
    "grade9swdapplicants1": "157",
    "grade9swdapplicantsperseat1": "10",
    "seats101": "No",
    "admissionspriority11": "Priority to continuing 8th graders",
    "admissionspriority21": "Then to New York City residents",
    "primary_address_line_1": "227-243 West 61st Street",
    "city": "Manhattan",
    "zip": "10023",
    "state_code": "NY",
    "borough": "MANHATTAN",
    "latitude": "40.772007",
    "longitude": "-73.987479",
    "community_board": "7",
    "council_district": "6",
    "census_tract": "151",
    "bin": "1030328",
    "bbl": "1011540108",
    "nta": "Lincoln Square"
}

]

""".data(using: .utf8)!
    
    let expectedLatitude = "40.688831"
      
      // act
       do {
        let schoolCoordinates = try JSONDecoder().decode([School].self, from: jsonData)
        // assert
        let coordinate = schoolCoordinates.first?.latitude
        XCTAssertEqual(expectedLatitude, coordinate)
      } catch {
        XCTFail("decoding error: \(error)")
      }
    

    
    
}
}
